import aiframework as ai

# if we give as input (0, 0) it says: returned a result with an exception set (SystemError: <built-in function Point>)

i = ai.Point(1, 0)
print(i)
